package vista;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class Facturaa extends javax.swing.JPanel {

    /**
     * Creates new form Facturaa
     */
    public Facturaa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo_fac = new javax.swing.JPanel();
        Titulo_factura = new javax.swing.JLabel();
        lblnumfac = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lblnumfacV = new javax.swing.JLabel();
        lblfechaV = new javax.swing.JLabel();
        Datos_productos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        txt_idproducto = new javax.swing.JTextField();
        txt_producto = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        btn_agregar = new javax.swing.JButton();
        btn_quitar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        ropaP = new javax.swing.JButton();
        ropaP1 = new javax.swing.JButton();
        ropaCH = new javax.swing.JButton();
        ropaCH1 = new javax.swing.JButton();
        ropaCm = new javax.swing.JButton();
        ropacm1 = new javax.swing.JButton();
        ropabl = new javax.swing.JButton();
        ropabl1 = new javax.swing.JButton();
        Datos_cliente = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_foto = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        txt_nombres = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_subtotal = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_iva = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_factura = new javax.swing.JTable();

        Titulo_factura.setText("FACTURA");

        lblnumfac.setText("N° FACT:");

        lblfecha.setText("FECHA:");

        lblfechaV.setText(" ");

        javax.swing.GroupLayout Titulo_facLayout = new javax.swing.GroupLayout(Titulo_fac);
        Titulo_fac.setLayout(Titulo_facLayout);
        Titulo_facLayout.setHorizontalGroup(
            Titulo_facLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Titulo_facLayout.createSequentialGroup()
                .addGroup(Titulo_facLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Titulo_facLayout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(Titulo_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblnumfac, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Titulo_facLayout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Titulo_facLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblfechaV, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnumfacV, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Titulo_facLayout.setVerticalGroup(
            Titulo_facLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Titulo_facLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Titulo_facLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnumfacV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Titulo_facLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Titulo_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblnumfac, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Titulo_facLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfechaV, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Datos_productos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Productos");
        Datos_productos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 69, 26));

        jLabel2.setText("Buscar:");
        Datos_productos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 62, 25));

        jLabel3.setText("ID_Producto:");
        Datos_productos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 30));

        jLabel4.setText("Producto:");
        Datos_productos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 71, 24));

        jLabel5.setText("Cantidad:");
        Datos_productos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));
        Datos_productos.add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 97, -1));
        Datos_productos.add(txt_idproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 89, -1));
        Datos_productos.add(txt_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 124, -1));
        Datos_productos.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 55, -1));
        Datos_productos.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        btn_agregar.setText("Agregar");
        Datos_productos.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 60, 30));

        btn_quitar.setText("Quitar");
        btn_quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitarActionPerformed(evt);
            }
        });
        Datos_productos.add(btn_quitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 60, 30));

        jPanel8.setBackground(new java.awt.Color(235, 235, 246));

        ropaP.setBorder(null);
        ropaP.setContentAreaFilled(false);

        ropaP1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ropaP1.setContentAreaFilled(false);

        ropaCH.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ropaCH.setContentAreaFilled(false);

        ropaCH1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ropaCH1.setContentAreaFilled(false);

        ropaCm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ropaCm.setContentAreaFilled(false);

        ropacm1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ropacm1.setContentAreaFilled(false);

        ropabl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ropabl.setContentAreaFilled(false);

        ropabl1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ropabl1.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(ropaP, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ropaP1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ropaCH, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ropaCH1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(ropaCm, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ropacm1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ropabl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ropabl1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ropaP, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ropaP1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ropaCH, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ropaCH1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ropaCm, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ropacm1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ropabl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ropabl1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Datos_productos.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        Datos_cliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Datos Cliente");
        Datos_cliente.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 6, -1, -1));

        jLabel7.setText("Cedula:");
        Datos_cliente.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 38, 53, 24));

        jLabel8.setText("Nombres:");
        Datos_cliente.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel9.setText("Apellidos:");
        Datos_cliente.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel10.setText("Telefono:");
        Datos_cliente.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel12.setText("Sub Total:");
        Datos_cliente.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 377, -1, -1));

        jLabel13.setText("IVA 12%:");
        Datos_cliente.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 407, -1, -1));

        jLabel14.setText("TOTAL:");
        Datos_cliente.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 431, -1, -1));
        Datos_cliente.add(lbl_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 111, 117));
        Datos_cliente.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 38, 124, -1));
        Datos_cliente.add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 123, -1));

        txt_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidosActionPerformed(evt);
            }
        });
        Datos_cliente.add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 123, -1));
        Datos_cliente.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 120, -1));

        txt_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subtotalActionPerformed(evt);
            }
        });
        Datos_cliente.add(txt_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 373, 122, -1));
        Datos_cliente.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 427, 122, -1));
        Datos_cliente.add(txt_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 403, 122, -1));

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        Datos_cliente.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 38, -1, -1));

        btn_guardar.setText("Guardar");
        Datos_cliente.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 373, 62, -1));

        btn_cancelar.setText("Cancelar");
        Datos_cliente.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 403, -1, -1));

        btn_imprimir.setText("Imprimir");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });
        Datos_cliente.add(btn_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 412, 62, -1));

        tbl_factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Cantidad", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tbl_factura);

        Datos_cliente.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 381, 143));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Datos_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Datos_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo_fac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo_fac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Datos_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Datos_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_quitarActionPerformed

    private void txt_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidosActionPerformed

    private void txt_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_subtotalActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Datos_cliente;
    private javax.swing.JPanel Datos_productos;
    private javax.swing.JPanel Titulo_fac;
    private javax.swing.JLabel Titulo_factura;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_quitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblfechaV;
    private javax.swing.JLabel lblnumfac;
    private javax.swing.JLabel lblnumfacV;
    private javax.swing.JButton ropaCH;
    private javax.swing.JButton ropaCH1;
    private javax.swing.JButton ropaCm;
    private javax.swing.JButton ropaP;
    private javax.swing.JButton ropaP1;
    private javax.swing.JButton ropabl;
    private javax.swing.JButton ropabl1;
    private javax.swing.JButton ropacm1;
    private javax.swing.JTable tbl_factura;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_idproducto;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_producto;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
